@authtoken = Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50IjoiYXBwMTIzIiwiYXBwbmFtZSI6ImFwcDEyMyIsImV4cCI6MTU4Mzg0NDQxMH0.f5OYYI5SDr_fe1gNWY5nK-vdjPkRndbPuWX6MXOzB70
###
POST https://api.api.kimatech.xyz/auth/init

###

POST https://api.kimatech.xyz/auth
Content-Type: application/json

{
    "account":"kimatech",
    "password":"oX9tMwONgheJCPubRBtt8hfA72o="
} 

###

POST https://api.kimatech.xyz/auth/update

###

POST https://api.kimatech.xyz/auth/update
Authorization: {{authtoken}}

###
GET https://api.kimatech.xyz/dev/hello
Authorization: {{authtoken}}

###
GET https://api.kimatech.xyz/dev/world
Authorization: {{authtoken}}

###

GET https://api.kimatech.xyz/auth/update
Authorization: {{authtoken}}
#